### PR TITLE
fix: use of _altered_model_name to enable change of structural parame…

### PR DESCRIPTION
**Pull request by MichaMans**
…ters

This fixes the use of the altered model name function to enable the change of structural paramters for the simulation.

Example:

```python
SIM_API = DymolaAPI(...) 
parameter_pipe = "AixLib.DataBase.Pipes.PE_X.DIN_16893_SDR11_d%s()"%da_m_flow[0]
SIM_API._structural_params = ["parameterPipe"]
parameters = {
        "m_flow_nominal": 8.5,
        "parameterPipe": parameter_pipe
    }
SIM_API.simulate(parameters=parameters)
```

### CODE REVIEW

**Review by FWuellhorst — APPROVED** [review]
@MichaMans : Feel free to merge if everything is ok from your side.

**Comment by FWuellhorst** [comment]
The new way of usage would be:

```python
SIM_API = DymolaAPI(...) 
parameter_pipe = "AixLib.DataBase.Pipes.PE_X.DIN_16893_SDR11_d%s()"%da_m_flow[0]
parameters = {
        "m_flow_nominal": 8.5,
        "parameterPipe": parameter_pipe
    }
SIM_API.simulate(parameters=parameters, structural_parameters=["parameterPipe"])
```

**Comment by FWuellhorst** [comment]
Tests should work once we merge https://github.com/RWTH-EBC/ebcpy/pull/26

**Comment by MichaMans** [comment]
@FWuellhorst should we merge this? Hows the procedure? Should I merge or do you?

**Comment by FWuellhorst** [comment]
I thought you are still working on this, definitely feel free to merge :) Thanks for the contribution!

**Pull request merged**
