### PR TITLE
Issue56 fix bounds fmu api

### PR DESCRIPTION
**Pull request by HvanderStok**
Solves #56, but `int` values from the `_to_bound()` function were always set to float in class `Variable()`. Changing `Union[float, int]` to `Any` solves the problem, but the check whether the correct type is used is no longer performed.

### CODE REVIEW

**Review by FWuellhorst — APPROVED** [review]
@HvanderStok:
Thanks for the fix! I added a validator to ensure users only pass floats and ints to the variables value. Check my solution. Afterwards, feel free to merge. Don't confuse yourself with the CI, it is currently broke.

**Comment by HvanderStok** [comment]
@FWuellhorst: 
The validator must be executed for min and max and not for value, because a variable can also be of type bool or str. Also, in the validator `isinstance(value, (float, int)` returns true for bool values, since bool inherits from int. I have fixed the problems, but it is still the case that bool variables get their bounds set to minus and plus infinity, although they actually have no limits. What is your opinion about this?

**Comment by FWuellhorst** [comment]
@HvanderStok : Thanks for noticing. I refactored the to_bounds method into the validator to avoid future confusion. Further, I added some tests to ensure it does not break again. Please check and review if some cases are missing from your point of view.

**Comment by HvanderStok** [comment]
I tested your new changes with a fmu model and everything works. The new standard bounds for the different types also make more sense now. Thanks for the fix.

**Pull request merged**
